apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-pvv-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sqldata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tb-pvc-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi